# Generated by Django 4.1.2 on 2022-10-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
